title:              Plume Quantique
email:              amlamanangekevin@gmail.com
author:             Ange Kevin Amlaman
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenue dans mon esprit, où se mèlent science-fiction, cinéma, littérature avec passion.
#baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                https://charveey.github.io

# Social Profiles
twitter_username:   im_kveen
github_username:    charveey
facebook_username:  charveey
instagram_username:  im_kveen
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-87BEBTNMK3 # out your google-analytics code


# Localization
date_format: "%d %B %Y"
lang: "fr"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag

defaults:
  -
    scope:
      path:            "img/**"
    values:
      sitemap:         false
  
  # You can use the following to enable claps on all posts.
  - 
    scope:
      type:            posts
    values:
      # https://applause-button.com/
      applause_button:       true

  # SEO tags
twitter:
  username: im_kveen
  card: summary
tagline: De la science-fiction, du cinéma & des livres le tout avec passion.
logo: "/img/bg/logo.svg"
